package com.eams.enums;

public enum NetworkDeviceCategory {
ACCESS_SWITCH, DISTRIBUTION_SWITCH, CORE_SWITCH, ROUTER, FIREWALL,
    WIRELESS_AP, WIRELESS_CONTROLLER, LOAD_BALANCER, IDS_IPS, VPN_CONCENTRATOR, OTHER
}
