-- SOFTWARE APPLICATIONS EXTENDED TABLE
CREATE TABLE asset_extended_applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL UNIQUE REFERENCES assets(id),
    app_name VARCHAR(255) NOT NULL,
    version_number VARCHAR(50) NOT NULL,
    version_release_date DATE NOT NULL,
    hosting_type VARCHAR(20) NOT NULL,
    hosting_institution VARCHAR(255),
    function_description TEXT NOT NULL,
    licence_id UUID REFERENCES licences(id),
    licence_count INTEGER NOT NULL,
    used_seats INTEGER NOT NULL DEFAULT 0,
    licence_type VARCHAR(30) NOT NULL,
    licence_expiry_date DATE,
    support_contract_ref VARCHAR(100),
    support_expiry_date DATE,
    host_server_ids UUID[],
    database_ids UUID[],
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- DATABASES EXTENDED TABLE
CREATE TABLE asset_extended_databases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL UNIQUE REFERENCES assets(id),
    db_engine VARCHAR(30) NOT NULL,
    engine_version VARCHAR(50) NOT NULL,
    patch_level VARCHAR(50),
    host_server_id UUID REFERENCES assets(id),
    parent_application_ids UUID[],
    data_classification VARCHAR(20) NOT NULL,
    backup_schedule TEXT NOT NULL,
    last_backup_verified_date DATE NOT NULL,
    encryption_at_rest VARCHAR(10) NOT NULL,
    encryption_in_transit BOOLEAN NOT NULL,
    tls_version VARCHAR(10),
    rto_minutes INTEGER,
    rpo_minutes INTEGER,
    licence_id UUID REFERENCES licences(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- SERVERS EXTENDED TABLE
CREATE TABLE asset_extended_servers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL UNIQUE REFERENCES assets(id),
    server_type VARCHAR(30) NOT NULL,
    hypervisor_platform VARCHAR(30),
    host_server_id UUID REFERENCES assets(id),
    manufacturer VARCHAR(100) NOT NULL,
    model_number VARCHAR(150) NOT NULL,
    serial_number VARCHAR(100) NOT NULL,
    os_name VARCHAR(150) NOT NULL,
    os_version VARCHAR(100) NOT NULL,
    os_release_date DATE NOT NULL,
    os_eos_date DATE,
    last_patch_date DATE NOT NULL,
    next_patch_date DATE,
    cpu_count SMALLINT NOT NULL,
    total_cores SMALLINT NOT NULL,
    ram_gb INTEGER NOT NULL,
    storage_gb INTEGER NOT NULL,
    storage_type VARCHAR(20),
    mgmt_ip_address INET NOT NULL,
    vlan_assignment VARCHAR(255),
    server_role VARCHAR(50) NOT NULL,
    dr_counterpart_id UUID REFERENCES assets(id),
    backup_policy_ref VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- NETWORK DEVICES EXTENDED TABLE
CREATE TABLE asset_extended_network_devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL UNIQUE REFERENCES assets(id),
    device_category VARCHAR(50) NOT NULL,
    manufacturer VARCHAR(100) NOT NULL,
    model_number VARCHAR(150) NOT NULL,
    serial_number VARCHAR(100) NOT NULL,
    mgmt_ip_address INET NOT NULL,
    firmware_version VARCHAR(100) NOT NULL,
    firmware_release_date DATE NOT NULL,
    last_firmware_update DATE NOT NULL,
    firmware_eos_date DATE,
    next_firmware_window DATE,
    isp_carrier VARCHAR(150),
    licence_type VARCHAR(50) NOT NULL,
    licence_id UUID REFERENCES licences(id),
    licence_expiry_date DATE,
    nac_status VARCHAR(20),
    vlan_assignment TEXT,
    uplink_device_ids UUID[],
    downlink_device_ids UUID[],
    rack_location_id UUID REFERENCES locations(id),
    support_contract_ref VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- CLIENT DEVICES EXTENDED TABLE
CREATE TABLE asset_extended_client_devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL UNIQUE REFERENCES assets(id),
    device_type VARCHAR(30) NOT NULL,
    manufacturer VARCHAR(100) NOT NULL,
    model VARCHAR(150) NOT NULL,
    serial_number VARCHAR(100) NOT NULL,
    mac_wired MACADDR NOT NULL,
    mac_wireless MACADDR,
    year_of_purchase SMALLINT NOT NULL,
    year_of_deployment SMALLINT NOT NULL,
    os_name VARCHAR(150) NOT NULL,
    os_patch_level VARCHAR(100) NOT NULL,
    vlan SMALLINT,
    switch_port VARCHAR(100),
    disk_encrypted BOOLEAN NOT NULL,
    encryption_tool VARCHAR(50),
    av_edr_name VARCHAR(150) NOT NULL,
    last_vuln_scan_date DATE NOT NULL,
    vuln_scan_source VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);